import './router';
import './application';
import './errorHanlders';
import './loginPageHandlers';
import './regSubmitHandler';
import './regFormHandlers';
import './headerHandlers';
import './profilePageHandlers';
import './productPageHandlers';
import './catalogPageHandlers';
import './basketPageHandlers';
import './aboutPageHandlers';
import './fillProductPage';
import './productModalHandlers';
import './filterSubmitHandler';
import './paginatorHandlers';
import './filterResetHandler';
import './searchHandler';
import './headerBasketHandlers'
